### ISSUE TITLE
как насчёт того, чтобы усовершенствовать расширение?

### ISSUE THREAD

**Issue by MrDoni98** [ntaklive/moodle_quiz_solver#1]
Приветствую, я собирал базу ответов через python и оформял в pdf, когда собрался написать расширение, решил сперва поискать готовые и нашёл твоё(ваше). Если тебе(вам) это ещё интересно, то хотел бы поделится идеями.
Первый момент, не на всех тестах отображаются верные ответы после прохождения. В таком случае можно проверять полученный балл за вопрос и в базе уже указывать верными те, что отмечены пользователем. Второй момент, если у вопроса есть кнопка "отметить вопрос", то можно получить qid вопроса в базе теста(курса) что сократит процесс проверки вопроса во время прохождения нового теста до сравнения этого qid
![image](https://user-images.githubusercontent.com/10742315/214192140-98beb245-8c65-47d0-8337-087b9a24ebcf.png)
![image](https://user-images.githubusercontent.com/10742315/214192231-edd26dec-beb5-4fb3-89cb-36407df76afe.png)

**Comment by ntaklive** [comment]
Доброго времени суток! Для меня нет смысла развивать данное расширение, т.к. я уже выпускной курс :). Оно было написано для того, чтобы сжульничать на одном из тестов. Это тестирование состояло из 4х отдельных тестов по 50 вопросов, к которым были тренировочные тесты из ~300 вопросов в каждом. Оттуда вручную (показать все вопросы) парсились правильные ответы и заносились в базу.
Это обуславливает то, что база выглядит так, как сейчас, делая поиск полностью по тексту вопроса и тексту ответов, а не учитывает qid или ещё что-то.
Поэтому планов нет, но надеюсь, что Вам чем-то помогут мои наработки, если захотите допилить функционал, либо написать своё.

**Comment by MrDoni98** [comment]
Так и подумал что выпустили)) У самого последний год как это может пригодится. Спасибо. Наработки определённо помогут😋
